language: python
cache: pip
python:
- 3.6
- 3.7
- 3.8
- 3.9
matrix:
  include:
  - stage: static analysis
    python: 3.9
    script: tox -e static-analysis
  - stage: integration test
    python: 3.9
    script: tox -e py39-tests -- test/integrationtest
  - stage: deploy
    name: Deploy to PyPI
    deploy:
      provider: pypi
      username: __token__
      password:
        secure: aJPDLwOFUB6b6bmk5a5AmtuvhIvEu5FSmS8zeQOAIngbvOc7YiIcI2U/CZJjRKaTjfR1rjlkPa0epEXAnMQ0UFzeDHhG34CG9Wn2rHqvxo6+6J5tIRLNUYwGna85z9oJyayZOnY8h1AOnmqNQIKMNWW1CPjyuxhyafQ6mM2e09fVa4lwElBNNAE6fknZmUyJY2/Hfp0256XNj28rba189XUjo5R0Tbn7YtasZcfLcRO3TOegjF3sUQy0wSZ5Wygx9N3P/cbg9nfE3tp/s6HtfD/wZ5uBXkDVeS/fjDzjWWKQNB5pGhf1bGcUtavBJeKxBVo448NBHcXOXIqEXwaFeJmeQx0SO48+XPIg81bx3x3fuGIJ9rv8km/5EaEO/AztTtfiKmbFlGdzv41mzfZuO+OQkacrJetIRZkPLs3QzDMtaiX0iayCFgfJ3Rq1kAS5dXKNgz7DerruH9r7Istt65sn4lx4aqvI3hY/JPk2Aqx+cO/YdHsnQgH/Mq6hm9Ctk6iibDOL2STnCIc46yWBfcSwwGtnKYjDJm8oKPkZ5hFdi6Wn2Oee+GNEoE8CQpztaj4fGvnUVHVBtb3hGrFVdYdfa6AXLoVvFeeLu3B43uqPm/6YZ3HcqnV88147t537Plfyq2XD7vwbIdrVzkFMZous4cKSvZCPGjVAndcwiCg=
      on:
        tags: true
      skip_existing: true
      distributions: sdist bdist_wheel
install:
- pip install tox-travis
- if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install coveralls; fi
script: tox
after_success:
- if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then coveralls; fi
