language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

matrix:
  include:
    - stage: static analysis
      python: 3.8
      env:
        - TOXENV=py38-static-analysis
    - stage: integration test
      python: 3.9
      env:
        - TOXENV=py39-tests -- test/integrationtest

install:
  - pip install tox-travis
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install coveralls; fi

script: tox

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then coveralls; fi
