language: python
cache: pip
python:
- 3.6
- 3.7
- 3.8
- 3.9
matrix:
  include:
  - stage: static analysis
    python: 3.9
    script: tox -e static-analysis
  - stage: integration test
    python: 3.9
    script: tox -e py39-tests -- test/integrationtest
  - stage: deploy
    name: Deploy to PyPI
    deploy:
      provider: pypi
      username: __token__
      password:
        secure: ayTjr2s/zwqxMI553Lnqdw6Jss/0yP2KBovAXe2j/A0yqtuaVcXFoGlSHA/OAnu9mKYDB2ndtg74ELtXdIWTh3K3QJneSdeYRFiLRE16N1Rit+banbZF/nj1Sghn79FNjPL810aJQy+/K0tcFpKNprIuQ8Nv/BtJ7cEAs2F8+oQjHp5TMr8yCnJ3UnJArCOONX9/mByvfcuyZBZpxlg2SvuHfXIa8OD8cMsSsRf+8U0z1lNmta4F7RduG+6oOj+uMZG3ZLaRi6FLaLheJcZvlvnWNh9u5hn4kAVw9hvnQ3AJlZyLcTprpzX9Lv8XK5xApNhfGwmX5HK441PkRkhTolv/JzsaFwtLfN5wufFhbIIWdhaNBQ4FH4M+x9v+UcV3mGBf0GqXbAyRQONAF5MmUlg4sjYEzystUE9pJPqvnS+EjNR8vL/FFXdyB+q57MLgQ/u17CyK3gqLZFvDS2SyNv0joD5Vyb20YevMXl9z2WW74WLocLx7rGnG67WfkmNPtzMzp/mU2Kr8UCYpX2asJbN2ED53zIJG0hkpdibGUY8peEEaFG8FC/uskMKqZPRtR/VPdkylYkr0FebRSd9eeitLFw6/fu54VtsRMxT1xbhLc9b4KcAy5VbJtbw21mbuemElKG57A4bdWQJboVTAhJyAD1U9AMBySZRXCsY0Yfc=
      on:
        tags: true
      skip_existing: true
      distributions: sdist bdist_wheel
install:
- pip install tox-travis
- if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install coveralls; fi
script: tox
after_success:
- if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then coveralls; fi
